language: node_js
node_js:
  - "8"
dist: trusty
addons:
  chrome: stable
sudo: required
before_install:
  - export CHROME_BIN=chromium-browser
script:
  - ./node_modules/.bin/grunt travis_ci_build
after_success:
  - ./node_modules/.bin/coveralls < coverage/karma/lcov.info
